### ISSUE TITLE
Example doesn't compile using the latest aide and Axum crates

### ISSUE THREAD

**Issue by itsbalamurali** [tamasfe/aide#91]
```bash
error[E0277]: the trait bound `axum::http::Response<Body>: axum_core::response::into_response::IntoResponse` is not satisfied
  --> api/src/docs.rs:45:86
   |
45 |   async fn serve_docs(Extension(api): Extension<Arc<OpenApi>>) -> impl IntoApiResponse {
   |  ______________________________________________________________________________________^
46 | |     Json(api).into_response()
47 | | }
   | |_^ the trait `axum_core::response::into_response::IntoResponse` is not implemented for `axum::http::Response<Body>`
   |
   = help: the following other types implement trait `axum_core::response::into_response::IntoResponse`:
             http_body::empty::Empty<axum::body::Bytes>
             axum_jsonschema::Json<T>
             JsonSchemaRejection
             http_body::combinators::box_body::BoxBody<axum::body::Bytes, E>
             http_body::combinators::box_body::UnsyncBoxBody<axum::body::Bytes, E>
             axum_extra::either::Either<E1, E2>
             axum_extra::either::Either3<E1, E2, E3>
             axum_extra::either::Either4<E1, E2, E3, E4>
           and 138 others
   = note: required for `axum::http::Response<Body>` to implement `IntoApiResponse`

```

**Comment by Wicpar** [comment]
There probably is a version issue, i'll check them before the next release. Also the example could just return without the into_response() i'll rework that too

**Comment by Wicpar** [comment]
it was working on 0.13, it's released now.

**Comment by itsbalamurali** [comment]
Thanks @Wicpar
