### ISSUE TITLE
axum Query stopped working with aide 0.14 / axum 0.8, axum-extra's Query works

### ISSUE THREAD

**Issue by mguentner** [tamasfe/aide#178]
After upgrading to aide 0.14 with axum 0.8, a route using axum's `Query` stops working with the following error:

```
error[E0277]: the trait bound `fn(axum::extract::Query<Example>) -> impl Future<Output = impl IntoApiResponse> {axum}: OperationHandler<_, _>` is not satisfied
   --> src/main.rs:47:33
    |
47  |         .api_route("/axum", get(axum))
    |                             --- ^^^^ the trait `OperationHandler<_, _>` is not implemented for fn item `fn(axum::extract::Query<Example>) -> impl Future<Output = impl IntoApiResponse> {axum}`
    |                             |
    |                             required by a bound introduced by this call
    |
    = help: the trait `OperationHandler<I, O>` is implemented for `Layered<L, H, T, S>`
note: required by a bound in `aide::axum::routing::get`
   --> /home/max/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aide-0.14.0/src/axum/routing.rs:345:1
    |
345 | method_router_top_level!(get, get_with);
    | ^^^^^^^^^^^^^^^^^^^^^^^^^---^^^^^^^^^^^
    | |                        |
    | |                        required by a bound in this function
    | required by this bound in `get`
    = note: this error originates in the macro `method_router_top_level` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `aide_reproduce` (bin "aide_reproduce") due to 1 previous error
```

Switching to [Query of axum-extra](https://docs.rs/axum-extra/latest/axum_extra/extract/struct.Query.html) works.

# How to reproduce

The following compiles, remove the comment to trigger the bug.

```rust
use aide::{
    axum::{routing::get, ApiRouter, IntoApiResponse},
    openapi::{Info, OpenApi},
};
use axum::{extract::Query, Extension, Json};
use axum_extra::extract::Query as ExtraQuery;

use schemars::JsonSchema;
use serde::Deserialize;
use tokio::net::TcpListener;

#[derive(Deserialize, JsonSchema)]
struct Example {
    value: usize,
}

async fn axum(Query(query): Query<Example>) -> impl IntoApiResponse {
    query.value.to_string()
}

async fn axum_extra(ExtraQuery(query): ExtraQuery<Example>) -> impl IntoApiResponse {
    query.value.to_string()
}

async fn serve_api(Extension(api): Extension<OpenApi>) -> impl IntoApiResponse {
    Json(api)
}

#[tokio::main]
async fn main() {
    aide::generate::on_error(|error| {
        println!("{error}");
    });

    aide::generate::extract_schemas(true);

    let mut api = OpenApi {
        info: Info {
            description: Some("an example API".to_string()),
            ..Info::default()
        },
        ..OpenApi::default()
    };

    let app = ApiRouter::new()
        // uncomment following line to trigger bug
        //.api_route("/axum", get(axum))
        .api_route("/axum_extra", get(axum_extra))
        .route("/api.json", get(serve_api));

    let listener = TcpListener::bind("0.0.0.0:4000").await.unwrap();

    axum::serve(
        listener,
        app.finish_api(&mut api)
            .layer(Extension(api))
            .into_make_service(),
    )
    .await
    .unwrap();
}
```

```toml
[package]
name = "aide_reproduce"
version = "0.1.0"
edition = "2021"

[dependencies]
aide = { version = "0.14.0", features = ["axum", "macros", "axum-json", "axum-extra-query"]}
axum = { version =  "0.8.1" , features = ["query", "json", "macros"]}
axum-extra = { version = "0.10.0", features = ["query"]}
schemars = "0.8.21"
serde = { version = "1.0.217", features = ["derive"]}
tokio = { version = "1.43.0", features = ["rt-multi-thread"]}
```

# Obeservation:

When you remove `JsonSchema` from the derives for  `Example`, you get the same error for `axum_extra` / axum-extra's `Query`.
